{
 "title": "LDES Server",
 "time": { "from": "2022-09-07T08:00:30.467Z", "to": "2022-09-07T08:12:48.669Z" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Member Flow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Ldes Members",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ldes_server_ingested_members_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Ldes Member in Fragmentation Queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ldes_server_members_to_fragment{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri!~\".*/actuator.*\", instance=~\"$instance\"}[$__rate_interval])/rate( http_server_requests_seconds_sum{uri!~\".*/actuator.*\", instance=~\"$instance\", status=\"200\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time per request",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate( http_server_requests_seconds_sum{uri!~\".*/actuator.*\", instance=~\"$instance\", status=\"200\"}[$__rate_interval]) / rate(http_server_requests_seconds_count{uri!~\".*/actuator.*\", instance=~\"$instance\", status=\"200\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "traces",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 21 },
     "targets": [
      {
       "query": "e76746e52938f81dee01b052e0419de5",
       "service": "ldes-server"
      }
     ]
    }
   ]
  }
 ]
}